#!/bin/bash

##APT::Install-Recommends "0" ; APT::Install-Suggests "0" ; --> sudo nano /etc/apt/apt.conf

set -x;

apt-get update -yq

packages=(
  # can I haz sandwich?
  aspell-en
  hunspell-en-us
  hyphen-en-us

  aspell-nb
  hunspell-nb
  hyphen-nb

  # Apps
  ark
  dolphin
  gwenview
  kate
  kde-spectacle
  kmenuedit
  konsole
  okular
  qml-module-org-kde-newstuff
  systemsettings

  # Services
  bluedevil
  khotkeys
  kscreen
  kwalletmanager
  plasma-nm
  plasma-pa
  powerdevil
  polkit-kde-agent-1
  upower

  # DE
  kwin-x11
  plasma-desktop
  plasma-workspace
  sddm
  xserver-xorg-core
  xserver-xorg-input-libinput
  x11-xserver-utils
  x11-xkb-utils
  x11-utils

  # Theming
  breeze-gtk-theme
  kde-config-gtk-style
  kde-config-gtk-style-previwe
  sddm-theme-breeze

  # Libs and Plugins
  libqtspell-qt5-0
  qtvirtualkeyboard-plugin
  plasma-browser-integration
  plasma-runners-addons
  pulseaudio-module-bluetooth

  # Ark tooling
  unzip
)

arguments=(
   -y
   -q
  --no-install-recommends
)

apt-get install "${arguments[@]}" "${packages[@]}"
